Update UT
chauberahul1993/ODIM pull request #27
Opened 2022-05-31 05:50 UTC by chauberahul1993

2022-06-01 14:53 UTC, jeevan-kamkar approved these changes

2022-06-02 03:56 UTC, AngithCJ approved these changes

2022-06-02 03:58 UTC, hemkapoor approved these changes

2022-06-02 04:31 UTC, amar-shalgar requested changes

2022-06-02 04:31 UTC, amar-shalgar commented on svc-systems/chassis/update_test.go
> + * Copyright (c) 2020 Intel Corporation
Add HPE license

2022-06-02 04:48 UTC, chauberahul1993 commented on svc-systems/chassis/update_test.go
> + * Copyright (c) 2020 Intel Corporation
updated

2022-06-02 04:48 UTC, amar-shalgar approved these changes

2022-06-02 06:23 UTC, merged