ODIM-5533: Fixed Odimra service manager  empty @odata.id in the Certificates property
chauberahul1993/ODIM pull request #3
Opened 2022-02-03 11:19 UTC by chauberahul1993

ODIM-5533: Fixed Odimra service manager  empty @odata.id in the Certificates property

2022-02-03 11:39 UTC, amar-shalgar requested changes
Please address comments

2022-02-03 11:39 UTC, amar-shalgar commented on svc-managers/mgrmodel/manager.go
> +	// Certificates            dmtf.Certificates  `json:"Certificates,omitempty"`
Please remove commented out code

2022-02-03 12:08 UTC, jeevan-kamkar requested changes
Remove the other changes which are not part of this bug

2022-02-04 06:38 UTC, amar-shalgar approved these changes

2022-02-04 06:59 UTC, jeevan-kamkar approved these changes

2022-02-04 07:00 UTC, merged