DeliveryRetryPolicy added new property in event subscription
chauberahul1993/ODIM pull request #41
Opened 2022-07-01 11:11 UTC by chauberahul1993

2022-07-01 13:04 UTC, lpooja approved these changes

2022-07-01 13:24 UTC, jeevan-kamkar approved these changes

2022-07-04 07:17 UTC, amar-shalgar requested changes

2022-07-04 07:17 UTC, amar-shalgar commented on svc-events/events/common.go
> +	} else if request.DeliveryRetryPolicy == "TerminateAfterRetries" || request.DeliveryRetryPolicy == "SuspendRetries" || request.DeliveryRetryPolicy == "RetryForeverWithBackoff" {
can we check only what is allowed, instead of checking what is not allowed in DeliveryRetryPolicy

2022-07-04 10:58 UTC, amar-shalgar approved these changes

2022-07-04 10:59 UTC, merged