Odim-6783: Remove default subscription for each server add request
chauberahul1993/ODIM pull request #63
Opened 2022-10-31 10:58 UTC by chauberahul1993

2022-11-03 03:41 UTC, amar-shalgar requested changes

2022-11-03 03:41 UTC, amar-shalgar commented on svc-events/events/publishevttosubscriber.go
> +	if err = json.Unmarshal([]byte(requestData), &message); err != nil {
can this be avoided

2022-11-03 06:25 UTC, kavyamani596 commented on svc-events/events/evtsubscription.go
> +	// subscriptionID := uuid.New().String()
remove this fully

2022-11-03 06:27 UTC, chauberahul1993 commented on svc-events/events/evtsubscription.go
> +	// subscriptionID := uuid.New().String()
We are keeping this comment

2022-11-03 06:39 UTC, kavyamani596 approved these changes

2022-11-03 11:32 UTC, chauberahul1993 commented on svc-events/events/publishevttosubscriber.go
> +	if err = json.Unmarshal([]byte(requestData), &message); err != nil {
done

2022-11-03 11:59 UTC, hemkapoor approved these changes

2022-11-03 12:03 UTC, sriteja-sabbineni approved these changes

2022-11-04 05:21 UTC, amar-shalgar approved these changes

2022-11-04 05:21 UTC, merged